In [30]:
a = 10
b = 20
c = a + b
print c

30


In [31]:
mylist = ["apple" , "banana" , "guava"]
print mylist
thislist = list(("apple","banana","guava"))
print thislist

['apple', 'banana', 'guava']
['apple', 'banana', 'guava']


In [33]:
l = [1,2,3]
l2 = l*2
print l2

[1, 2, 3, 1, 2, 3]


In [32]:
l = [1,2,3]
l1 = [11,22,33]
l2 = l*2
l3 = l + l1
print l2,l3

[1, 2, 3, 1, 2, 3] [1, 2, 3, 11, 22, 33]


In [34]:
l = [1,2,3]
l1 = [11,22,33]
mylist = ["apple" , "banana" , "orange"]
newlist = [x if x != "banana" else "orange" for x in mylist]
print newlist

['apple', 'orange', 'orange']


In [35]:
list1 = ['physics' , 'chemistry' , 1997 , 2000]
list2 = [1,2,3,4,5,6,7]
print"list1[0] = ", list1[0]
print"list2[1:5] = ", list2[1:5]
print"list2[2:] = ", list2[2:]
print"list2[:2] = ", list2[:2]
print"list2[-2:] = ", list2[-2:]
print"list2[:-2] = ", list2[:-2]
print"list2[2:-2] = ", list2[2:-2]
print"list2[-2:2] = ", list2[-2:2]

list1[0] =  physics
list2[1:5] =  [2, 3, 4, 5]
list2[2:] =  [3, 4, 5, 6, 7]
list2[:2] =  [1, 2]
list2[-2:] =  [6, 7]
list2[:-2] =  [1, 2, 3, 4, 5]
list2[2:-2] =  [3, 4, 5]
list2[-2:2] =  []


In [36]:
list1 = ['physics','chemistry',1997,2000]
for i in list1:
    print(i)

physics
chemistry
1997
2000


In [37]:
list1 = ['physics','chemistry',1997,2000]
print list1
list1[2] = 100
print list1

['physics', 'chemistry', 1997, 2000]
['physics', 'chemistry', 100, 2000]


In [38]:
list1 = ['physics','chemistry',1997,2000]
print list1
list1[2] = 100
del list1[2];
print list1

['physics', 'chemistry', 1997, 2000]
['physics', 'chemistry', 2000]


In [39]:
list1 = ['physics','chemistry',1997,2000]
for i in list1:
    print(x)

orange
orange
orange
orange


In [40]:
list1 = ['physics','chemistry',1997,2000]
for i in range(len(list1)):
    print(list1[i])

physics
chemistry
1997
2000


In [41]:
list1 = ['physics','chemistry',1997,2000]
i = 0
while i < len(list1):
    print list1[i]
    i+=1

physics
chemistry
1997
2000


In [42]:
list1 = ['physics' , 'chemistry' , 1997 , 2000]
list2 = [1,2,3,4,5,6,7]
for x in list1:
    list2.append(x)
print list2

[1, 2, 3, 4, 5, 6, 7, 'physics', 'chemistry', 1997, 2000]


In [44]:
fruits = ['aaple', 'banana' , "cherry" ]
newlist0 = [x for x in range(10)]
newlist1 = [x for x in range(10) if x<5]
newlist2 = [x.upper() for x in fruits]

print newlist0,newlist1,newlist2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] [0, 1, 2, 3, 4] ['AAPLE', 'BANANA', 'CHERRY']


In [47]:
list1 = ["Python","Java",".Net","C","C++"]
print list1
list1.append("Ruby")
print list1
list1.extend("JS")
print list1
list1.insert(1,"Assembly")
print list1
list1.remove('C')
print list1
print sorted(list1)
print list1[::-1]

['Python', 'Java', '.Net', 'C', 'C++']
['Python', 'Java', '.Net', 'C', 'C++', 'Ruby']
['Python', 'Java', '.Net', 'C', 'C++', 'Ruby', 'J', 'S']
['Python', 'Assembly', 'Java', '.Net', 'C', 'C++', 'Ruby', 'J', 'S']
['Python', 'Assembly', 'Java', '.Net', 'C++', 'Ruby', 'J', 'S']
['.Net', 'Assembly', 'C++', 'J', 'Java', 'Python', 'Ruby', 'S']
['S', 'J', 'Ruby', 'C++', '.Net', 'Java', 'Assembly', 'Python']


In [54]:
bool("abc")
bool(123)

True

In [51]:
print bool(False)
print bool(None)
print bool(0)
print bool("")
print bool(())
print bool([])
print bool({})

False
False
False
False
False
False
False


In [55]:
def fn(mylist):
    mylist.append([1,2,3,4])
    print "Values inside my function : ",mylist
    return
mylist = [10,20,30]
fn(mylist)
print "Values outside my function : ",mylist

Values inside my function :  [10, 20, 30, [1, 2, 3, 4]]
Values outside my function :  [10, 20, 30, [1, 2, 3, 4]]


In [57]:
def printinfo(name , age = 35):
    print "Name : ",name
    print "Age : ",age
    return
printinfo("Parth")
printinfo("Parth" , 25)

Name :  Parth
Age :  35
Name :  Parth
Age :  25


In [60]:
def change(mylist):
    mylist = [0,1,2]
    print "Values inside my function : ",mylist
    return
mylist = [10,20,30]
change(mylist)
print "Values outside my function : ",mylist

Values inside my function :  [0, 1, 2]
Values outside my function :  [10, 20, 30]


In [61]:
x = 88

In [62]:
x

88

In [65]:
def change(*mylist):
    for i in mylist:
        print(i)
    return
change([10,20,30])
change(20)
change("C", "M" , "D" , "A")

[10, 20, 30]
20
C
M
D
A


In [70]:
sum = lambda arg1,arg2 : arg1+arg2

print sum(10,20)
print sum("Parth "," Shukla")
print sum([1,2,3],["One","two","three"])

30
Parth  Shukla
[1, 2, 3, 'One', 'two', 'three']


In [76]:
def myfun(n):
    return lambda a:a*n
mydoubler = myfun(2)
print mydoubler(2525252525)

5050505050


In [89]:
thisdict = {1:"Python",2:"android",3:"windows"}
print thisdict
print thisdict[2]
print thisdict[3]
print thisdict.keys()
print thisdict.values()
thisdict.update({4:"Black Berry"})
print thisdict
thisdict[4] = "Google"
print thisdict
dict4 = dict({1:'apple',2:'banana'})
print dict4
dict5 = dict([(1,'one'),(2,'two')])
print dict5

{1: 'Python', 2: 'android', 3: 'windows'}
android
windows
[1, 2, 3]
['Python', 'android', 'windows']
{1: 'Python', 2: 'android', 3: 'windows', 4: 'Black Berry'}
{1: 'Python', 2: 'android', 3: 'windows', 4: 'Google'}
{1: 'apple', 2: 'banana'}
{1: 'one', 2: 'two'}


In [90]:
marks = {}.fromkeys(['Maths', 'English', 'Science'],0)
print marks
for item in marks.items():
    print(item)
print(list(sorted(marks.keys())))

{'Maths': 0, 'Science': 0, 'English': 0}
('Maths', 0)
('Science', 0)
('English', 0)
['English', 'Maths', 'Science']


In [91]:
squares = {x:x*x for x in range(6)}
print squares
squares = {}
for x in range(6):
    squares[x] = x*x
print squares

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25}
{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [93]:
squares = {1:1, 3:9, 5:25, 7:49, 9:81}
print 1 in squares
print 2 not in squares
print 49 in squares
for i in squares:
    print squares[i]

True
True
False
1
9
81
25
49


In [94]:
my_information = {"name" : "Dionsyia" , "age" : 28 , "location" : "Athenes"}
city = my_information.pop('location')
print my_information
print city

{'age': 28, 'name': 'Dionsyia'}
Athenes


In [95]:
my_information = {"name" : "Dionsyia" , "age" : 28 , "location" : "Athenes"}
a = my_information.pop('occupation' , 'Not Found')
print my_information
print a

{'age': 28, 'name': 'Dionsyia', 'location': 'Athenes'}
Not Found


In [101]:
dic = {
    "child1" : {
        "name" : "Emil",
        "year" : 2004
    },
    "child2" : {
        "name" : "Tobias",
        "year" : 2011
    },
    "child3" : {
        "name" : "Linus",
        "year" : 2015
    }
}

print dic

aa = {"child11" : "child1", "child22" : "child2", "child33" : "child3"}
print aa

{'child1': {'name': 'Emil', 'year': 2004}, 'child2': {'name': 'Tobias', 'year': 2011}, 'child3': {'name': 'Linus', 'year': 2015}}
{'child22': 'child2', 'child11': 'child1', 'child33': 'child3'}


In [114]:
str1 = "Hello L&G"
print str1
str2 = "Hello " + "L&G"
print str2
str3 = 3*str1
print str3
print str1.replace("L&G","World")
x = str1.replace("L&G","World")
print str1
print x.upper()

Hello L&G
Hello L&G
Hello L&GHello L&GHello L&G
Hello World
Hello L&G
HELLO WORLD


In [105]:
str4 = "1,2,3,4,5,6"
str4.split(",")

['1', '2', '3', '4', '5', '6']

In [107]:
str8 = "       Hello World         "
print str8.rstrip()
print str8.lstrip()
print str8.strip()

       Hello World
Hello World         
Hello World


In [111]:
str6 = ""
str6.join(str1)

'Hello L&G'

In [121]:
txt = "the best things in life are free"
print "free" in txt
if "free" in txt:
    print "Yes, free is present"

print "expensive" not in txt

if "expensive" not in txt:
    print "No, expensive is present"

True
Yes, free is present
True
No, expensive is present


In [122]:
b = "Hello World!"
print b[2:5]
print b[:5]
print b[2:]
print b[-5:-2]

llo
Hello
llo World!
orl


In [124]:
age = 36
print "My name is John, and I'm " + str(age)
txt = "My name is John, and I'm {}"
print txt.format(age)
q = 3
i = 567
p = 49.95
myorder = "i want {} peices of item {} for {} dollars"
print myorder.

My name is John, and I'm 36
My name is John, and I'm 36


In [126]:
str1 = "Parth "
print str1 + 9

TypeError: cannot concatenate 'str' and 'int' objects

In [129]:
a,b,c,d = 10,20,30,40
def funA():
    a,b,c=100,200,300
    print "in fun a",a,b,c,d
    def funB():
        a,b=1000,2000,
        print "in fun b",a,b,c,d
        def funC():
            a=10000
            print "in fun c",a,b,c,d
        funC()
    funB()
funA()
print "In main ",a,b,c,d

in fun a 100 200 300 40
in fun b 1000 2000 300 40
in fun c 10000 2000 300 40
In main  10 20 30 40


In [132]:
import re
strings = "She sells sea shells on the sea shore"
print re.split(" ",strings)

['She', 'sells', 'sea', 'shells', 'on', 'the', 'sea', 'shore']


In [134]:
class Infant:
    "This is example class"
    pass
child = Infant()
help(child)

Help on instance of Infant in module __main__:

class Infant
 |  This is example class



In [135]:
class Infant :
    def Walk(self):
        print "statrted crawling"
    
child = Infant()
child.Walk()

statrted crawling


In [138]:
class Mom():
    def Walk(self):
        print("walk-mom")
        print("the address of self is ", id(self))
class Child(Mom):
    pass
child = Child()
child.Walk()
print("the address of self is ", id(child))

walk-mom
('the address of self is ', 82002184L)
('the address of self is ', 82002184L)


In [140]:
class Mom():
    def Walk(self):
        print "Walk-Mom"
        print "the address of self is ", id(self)
Mother = Mom()
print(type(Mom.Walk))
print(type(Mother.Walk))

<type 'instancemethod'>
<type 'instancemethod'>


In [142]:
class Example():
    def __init__(self):
        self.__private = "I'm private"
        self._protected = "I'm protected"
        self.public = "I'm public"
ob = Example()
print(ob.public)
print(ob._protected)
#print(ob.__private)

I'm public
I'm protected


In [143]:
class Example():
    def __init__(self):
        print("Object constructed")
    def __del__(self):
        print("Object Destroyed")
obj = Example()
del(obj)

Object constructed
Object Destroyed


In [144]:
class Date:
    def __init__(self,day,month,year):
        self.year = year
        self.month = month
        self.day = day
        
    @classmethod    
    def myd(cls,month,year,day):
        cls.day = day
        cls.month = month
        cls.year = year
        return cls(cls.day,cls.month,cls.year)
    
    @classmethod
    def ymd(cls,month,year,day):
        cls.day = day
        cls.month = month
        cls.year = year
        return cls(cls.day,cls.month,cls.year)
    
d1 = Date(17,4,2019)
print(d1.year,d1.month,d1.day)

d2 = Date(4,2018,15)
print(d2.year,d2.month,d2.day)

d3 = Date(2017,17,1)
print(d3.year,d3.month,d3.day)

print(d1.year)
print(d2.year)
print(d3.year)

(2019, 4, 17)
(15, 2018, 4)
(1, 17, 2017)
2019
15
1


In [23]:
import numpy as np
lst = [2,5,7,9]
x11 = np.array(lst)
y = np.array([lst,lst])
z = np.array([[2,4,6],[2,7,9]])
n1 = np.array([[2,4,6],[3,6,9],[1,2,3]])
n2 = 10*np.eye(4)
n3 = np.zeros(shape=(4,6))
n4 = 5*np.ones(shape=(3,5))
n5 = np.arange(10)
n6 = np.arange(-5,10)
n7 = np.random.rand(2,3,6)
n8 = np.random.randn(4,5)
print x
print"=============="
print y
print"=============="
print z
print"=============="
print n1
print"=============="
print n2
print"=============="
print n3
print"=============="
print n4
print"=============="
print n5
print"=============="
print n6
print"=============="
print n7
print"=============="
print n8
print np.__version__

[2 5 7 9]
[[2 5 7 9]
 [2 5 7 9]]
[[2 4 6]
 [2 7 9]]
[[2 4 6]
 [3 6 9]
 [1 2 3]]
[[10.  0.  0.  0.]
 [ 0. 10.  0.  0.]
 [ 0.  0. 10.  0.]
 [ 0.  0.  0. 10.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]
[0 1 2 3 4 5 6 7 8 9]
[-5 -4 -3 -2 -1  0  1  2  3  4  5  6  7  8  9]
[[[7.30536274e-01 2.97548036e-02 5.33534312e-01 9.11378825e-01
   2.51827106e-01 2.10763718e-01]
  [2.57667215e-01 1.63043550e-01 6.35648003e-01 8.91313234e-01
   5.78943117e-01 5.56620202e-02]
  [5.45453424e-03 5.73249424e-04 9.42645614e-01 5.77756041e-02
   1.44351652e-01 5.60637983e-01]]

 [[3.99200022e-01 4.47694971e-01 8.33220799e-01 1.81128795e-01
   4.32771771e-01 7.98626485e-01]
  [6.19521827e-01 2.27875320e-01 4.34037771e-01 6.45174585e-01
   4.27503486e-01 4.60596997e-02]
  [5.72839555e-01 9.35624391e-01 8.79133595e-01 6.58506504e-01
   1.68584720e-01 6.35733679e-02]]]
[[-0.27248784 -0.60299657  0.58980388  0.0955047

In [19]:
x11.shape

(4L,)

In [20]:
x11 

array([2, 5, 7, 9])

In [24]:
import numpy as np
arr = np.array([1,2,3,4,5], ndmin=5)
print arr
print arr.ndim

[[[[[1 2 3 4 5]]]]]
5


In [27]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print arr
print arr[2:]
print arr[:2]
print arr[:-2]
print arr[-2:]
print arr[3:5]

[1 2 3 4 5 6 7 8]
[3 4 5 6 7 8]
[1 2]
[1 2 3 4 5 6]
[7 8]
[4 5]


In [2]:
import numpy as np
arr = np.array([[1,2,3,4,5,6,7,8],[11,22,33,44,55,66,77,88]])
print arr
print arr[1,1:4]
print arr[0:2,2]
print arr[0:2,1:4]

[[ 1  2  3  4  5  6  7  8]
 [11 22 33 44 55 66 77 88]]
[22 33 44]
[ 3 33]
[[ 2  3  4]
 [22 33 44]]


In [37]:
import pandas as pd
pd.read_csv("D:\\New Microsoft Excel Worksheet.csv")

1       Astha  26-Jan
0  2      Hardik  21-Jan
1  3  Hrishikesh  19-Apr
2  4       Madhu  04-Apr
3  5      Mranal  02-Nov
4  6       Parth  16-Aug
5  7      Shreya  09-Jun

In [39]:
temp = [30,31,32,33,34,35,36,37,38,39,40,41]
mon = ["jan","feb","march","apr","may","june","july","aug","sept","oct","nov","dec"]
s1 = pd.Series(temp,mon)

In [40]:
s1

jan      30
feb      31
march    32
apr      33
may      34
june     35
july     36
aug      37
sept     38
oct      39
nov      40
dec      41
dtype: int64

In [41]:
s1[2:9]

march    32
apr      33
may      34
june     35
july     36
aug      37
sept     38
dtype: int64

In [42]:
df = pd.read_csv("D:\\New Microsoft Excel Worksheet.csv")

In [7]:
import pandas as pd
temp = [30,31,32,33,34,35,36,37,38,39,40,41]
mon = ["jan","feb","march","apr","may","june","july","aug","sept","oct","nov","dec"]
s1 = pd.Series(temp,mon)
table = pd.DataFrame(s1)
table['Rain'] = pd.Series([10,20,30,10,40,20,6,5,6,3,1,3],index = ["jan","feb","march","apr","may","june","july","aug","sept","oct","nov","dec"])
print table

        0  Rain
jan    30    10
feb    31    20
march  32    30
apr    33    10
may    34    40
june   35    20
july   36     6
aug    37     5
sept   38     6
oct    39     3
nov    40     1
dec    41     3


In [8]:
import numpy as np
import pandas as pd
df = pd.DataFrame()
print df

Empty DataFrame
Columns: []
Index: []


In [15]:
lst = [1,2,3,4,5,6,'a',2.0,'f']
print lst
print "==================="
df = pd.DataFrame(lst)
print df
print "==================="
lst1 = [1,2,3,4,5,6,'a',2.0,'f']
print lst
df = pd.DataFrame(lst1,index = [99,98,97,96,95,94,93,92,91])
print df
print "==================="
data = [[1,"Parth"],[2,"Shreya"],[3,"Mranal"],[4,"Hrishkesh"]]
df = pd.DataFrame(data)
print df
print "==================="
for x,n in df.iteritems():
    print x,n
print "==================="

[1, 2, 3, 4, 5, 6, 'a', 2.0, 'f']
   0
0  1
1  2
2  3
3  4
4  5
5  6
6  a
7  2
8  f
[1, 2, 3, 4, 5, 6, 'a', 2.0, 'f']
    0
99  1
98  2
97  3
96  4
95  5
94  6
93  a
92  2
91  f
   0          1
0  1      Parth
1  2     Shreya
2  3     Mranal
3  4  Hrishkesh
0 0    1
1    2
2    3
3    4
Name: 0, dtype: int64
1 0        Parth
1       Shreya
2       Mranal
3    Hrishkesh
Name: 1, dtype: object


In [16]:
for x,n in df.iteritems():
    print x,n

0 0    1
1    2
2    3
3    4
Name: 0, dtype: int64
1 0        Parth
1       Shreya
2       Mranal
3    Hrishkesh
Name: 1, dtype: object


In [19]:
df = pd.DataFrame(np.random.randn(4,4),index = [6,7,8,9],columns = ['col1','col2','col3','col4'])
print df
for row_index,row in df.iterrows():
    print row_index,row
for row_index,row in df.iteritems():
    print row_index,row

       col1      col2      col3      col4
6  0.076368 -0.359217 -1.277019 -1.124506
7 -1.903112  0.334928 -1.028459 -1.344166
8  0.571965 -0.456533 -0.616997 -0.750799
9  0.270075 -2.015854 -0.021814  0.953672
6 col1    0.076368
col2   -0.359217
col3   -1.277019
col4   -1.124506
Name: 6, dtype: float64
7 col1   -1.903112
col2    0.334928
col3   -1.028459
col4   -1.344166
Name: 7, dtype: float64
8 col1    0.571965
col2   -0.456533
col3   -0.616997
col4   -0.750799
Name: 8, dtype: float64
9 col1    0.270075
col2   -2.015854
col3   -0.021814
col4    0.953672
Name: 9, dtype: float64
col1 6    0.076368
7   -1.903112
8    0.571965
9    0.270075
Name: col1, dtype: float64
col2 6   -0.359217
7    0.334928
8   -0.456533
9   -2.015854
Name: col2, dtype: float64
col3 6   -1.277019
7   -1.028459
8   -0.616997
9   -0.021814
Name: col3, dtype: float64
col4 6   -1.124506
7   -1.344166
8   -0.750799
9    0.953672
Name: col4, dtype: float64


In [20]:
for row_index,row in df.iterrows():
    print row_index,row

6 col1    0.076368
col2   -0.359217
col3   -1.277019
col4   -1.124506
Name: 6, dtype: float64
7 col1   -1.903112
col2    0.334928
col3   -1.028459
col4   -1.344166
Name: 7, dtype: float64
8 col1    0.571965
col2   -0.456533
col3   -0.616997
col4   -0.750799
Name: 8, dtype: float64
9 col1    0.270075
col2   -2.015854
col3   -0.021814
col4    0.953672
Name: 9, dtype: float64


In [21]:
for row_index,row in df.iteritems():
    print row_index,row

col1 6    0.076368
7   -1.903112
8    0.571965
9    0.270075
Name: col1, dtype: float64
col2 6   -0.359217
7    0.334928
8   -0.456533
9   -2.015854
Name: col2, dtype: float64
col3 6   -1.277019
7   -1.028459
8   -0.616997
9   -0.021814
Name: col3, dtype: float64
col4 6   -1.124506
7   -1.344166
8   -0.750799
9    0.953672
Name: col4, dtype: float64


In [23]:
for row in df.itertuples():
    print row

Pandas(Index=6L, col1=0.07636773287851707, col2=-0.3592169286503022, col3=-1.2770191534044448, col4=-1.1245063274726472)
Pandas(Index=7L, col1=-1.9031123728392059, col2=0.3349277964875046, col3=-1.0284585979760155, col4=-1.3441660054137385)
Pandas(Index=8L, col1=0.5719652430321405, col2=-0.45653276277703775, col3=-0.6169972101120113, col4=-0.7507994228023044)
Pandas(Index=9L, col1=0.27007474132372983, col2=-2.015853746886435, col3=-0.02181420595737471, col4=0.9536724792296143)


In [36]:
A = {'A':['a','b','c'],'B' : [1,2,3], 'C':[2014,2015,2016],'D':["AA","BB","yy"]}
print A
df = pd.DataFrame(A)
print df
df = pd.DataFrame(A,index = [1,2,4])
print df
#lstdis = [{'A':['a','b','c']},{'B':[1,2,3]},'C':{'AA','BB','CC'}]
data = [{'a':[1,2],'b':2},{'a':5,'b':10,'c':20}]
data2 = [{'a':['a','a','c']},{'a':5,'b':10,'c':20},{'a':11,'h':1,'g':6}]
df = pd.DataFrame(data2,index=['first','second','th'])
print df

{'A': ['a', 'b', 'c'], 'C': [2014, 2015, 2016], 'B': [1, 2, 3], 'D': ['AA', 'BB', 'yy']}
   A  B     C   D
0  a  1  2014  AA
1  b  2  2015  BB
2  c  3  2016  yy
   A  B     C   D
1  a  1  2014  AA
2  b  2  2015  BB
4  c  3  2016  yy
                a     b     c    g    h
first   [a, a, c]   NaN   NaN  NaN  NaN
second          5  10.0  20.0  NaN  NaN
th             11   NaN   NaN  6.0  1.0


In [33]:
lst = [[1,2,3],[11,22,33]]
df = pd.DataFrame(lst,index=['m','n'],dtype = float)
df

0     1     2
m   1.0   2.0   3.0
n  11.0  22.0  33.0

In [31]:
data2 = [{'a':['a','a','c']},{'a':5,'b':10,'c':20},{'a':11,'h':1,'g':6}]
df = pd.DataFrame(data2,index=['first','second','th'])
df.fillna(value=5)

a     b     c    g    h
first   [a, a, c]   5.0   5.0  5.0  5.0
second          5  10.0  20.0  5.0  5.0
th             11   5.0   5.0  6.0  1.0

In [38]:
data = [['Alex',10],['Bob',12],['Clarke',13]]
df = pd.DataFrame(data,columns=['Name','Age'],index=[5,6,7],dtype=float)
df

Name   Age
5    Alex  10.0
6     Bob  12.0
7  Clarke  13.0

In [40]:
data = [[10,'Alex'],[12,'Bob'],[13,'Clarke']]
df = pd.DataFrame(data,columns=['Age','Name'],index=[5,6,7],dtype=float)
df

Age    Name
5  10.0    Alex
6  12.0     Bob
7  13.0  Clarke